name: novapost
description: "novapost"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

sdk: &sdk_version ^3.9.2

auth_repository: &auth_repository_version ^0.0.1
telegram_repository: &telegram_repository_version ^0.0.1

json_annotation: &json_annotation_version ^4.9.0
json_serializable: &json_serializable_version ^6.10.0

environment:
  sdk: *sdk_version

workspace:
  - packages/account_repository
#  - utility/partner_repository
  - packages/profile_repository

melos:
#  useRootAsPackage: false
  categories:
    app:
      - "."
    packages:
      - utility/partner_repository
      - packages/account_repository
      - packages/profile_repository
      - '*'
  command:
    bootstrap:
#      environment:
#        sdk: *sdk_version
#        flutter: ">=3.0.0 <4.0.0"
      dependencies:
        auth_repository: *auth_repository_version
        telegram_repository: *telegram_repository_version
        json_annotation: *json_annotation_version
        json_serializable: *json_serializable_version



# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.


url_launcher: &url_launcher_version ^6.3.0
provider: &provider ^6.1.5

dependencies:
  auth_repository: *auth_repository_version
  telegram_repository: *telegram_repository_version

  provider: *provider
  url_launcher: *url_launcher_version

  delivery_repository:
    path: packages/delivery_repository
  account_repository:
    path: packages/account_repository

  flutter_web_plugins:
    sdk: flutter

  flex_color_scheme: ^8.3.0
  package_info_plus: ^8.0.2
  dropdown_search: ^5.0.6
  web_socket_channel: ^3.0.2
  dcli: ^7.0.5
  dio: ^5.4.3
  fast_csv: ^0.2.6
  get_it: ^8.2.0
  hive: ^2.2.3
  logger: ^2.0.2+1
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.3.1
  spreadsheet_decoder: ^2.2.0
  shared_preferences: ^2.3.2
  responsive_framework: ^1.4.0
  intl: ^0.20.2
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  global_configuration: ^2.0.0
  dio_cache_interceptor: ^3.5.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.1
  decimal: ^3.2.4
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  two_dimensional_scrollables: ^0.3.1
  responsive_builder: ^0.7.1
  image_picker: ^1.0.4
  file_picker: ^10.1.2
  melos: ^7.1.1
  carousel_slider: ^5.1.1
  http: ^1.5.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  locale:
    path: utility/locale
  locale_catalog:
    path: utility/locale_catalog
  core:
    path: utility/core
  auth:
    path: utility/auth
  widgets:
    path: utility/widgets
  chat:
    path: utility/chat
  notification:
    path: utility/notification
  payment:
    path: utility/payment

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  retrofit_generator: ^10.0.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  freezed: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/