name: account_repository
description: account_repository
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

auth_repository: &auth_repository_version ^0.0.1

uuid: &uuid ^4.5.1

dependencies:
  auth_repository: *auth_repository_version
  profile_repository:
    path: ../profile_repository

  uuid: *uuid
  http: ^1.5.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^7.1.2
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5


dev_dependencies:
  test: ^1.17.11
  build_runner: ^2.4.6
