name: delivery_repository
description: delivery_repository
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2

auth_repository: &auth_repository_version ^0.0.1

json_annotation: &json_annotation_version ^4.9.0
json_serializable: &json_serializable_version ^6.10.0

uuid: &uuid ^4.5.1

dependencies:
  auth_repository: *auth_repository_version
  json_annotation: *json_annotation_version
  json_serializable: *json_serializable_version
  parcel_repository:
    path: ../parcel_repository

  uuid: *uuid
  http: ^1.5.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^7.1.2
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5


dev_dependencies:
  test: ^1.17.11
  build_runner: ^2.4.6
